parser: babel-eslint
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-native/all
  - plugin:import/warnings
  - plugin:import/errors
  - plugin:prettier/recommended
plugins:
  - react
  - react-native
  - import
  - prettier
rules:
  react/prop-types: off
  import/order: error
  prettier/prettier:
    - error
    -
      semi: false
      printWidth: 100
      singleQuote: true
settings:
  import/ignore:
    - expo
    - react-native-cell-components
env:
  es6: true
  node: true
  jest: true
  browser: true
  react-native/react-native: true
parserOptions:
  sourceType: module
  ecmaVersion: 2018
  ecmaFeatures:
    experimentalObjectRestSpread: true
    experimentalDecorators: true
    classes: true
    jsx: true
